import { useState, useEffect, useCallback } from 'react';
import { ref, onValue, set } from 'firebase/database';
import { db, DB_KEY } from './firebase';
import { useLang } from './context/LanguageContext';
import { TODAY, emptyDay, buildDaySections } from './data/mealPlan';
import { getTodayCookPattern } from './data/cookRecipes';
import { NUTRITION } from './data/nutrition';

import Header from './components/Header';
import SyncBar from './components/SyncBar';
import BottomNav from './components/BottomNav';
import BPAlert from './components/BPAlert';
import CookToast from './components/CookToast';

import TodayPage from './pages/TodayPage';
import HistoryPage from './pages/HistoryPage';
import CookPage from './pages/CookPage';
import AvoidPage from './pages/AvoidPage';

import ItemActionModal from './components/modals/ItemActionModal';
import UndoModal from './components/modals/UndoModal';
import BPUndoModal from './components/modals/BPUndoModal';
import ResetModal from './components/modals/ResetModal';
import AddExtraModal from './components/modals/AddExtraModal';
import HistoryDetailModal from './components/modals/HistoryDetailModal';
import HowToCookModal from './components/modals/HowToCookModal';

const cookPattern = getTodayCookPattern();

function buildAllItems(sections) {
  const all = [];
  if (!sections) return all;
  ['morning', 'afternoon', 'evening', 'night', 'medicine'].forEach(s => {
    if (sections[s]) all.push(...sections[s]);
  });
  return all;
}

function nowStr() {
  return new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
}

function generateReport(dayKey, dayData, allItems) {
  const items = dayData.items || {};
  const extras = dayData.extras || [];
  const bp = dayData.bp;
  const bpTime = dayData.bpTime;

  const given = allItems.filter(i => items[i.id] && items[i.id].status === 'done');
  const skipped = allItems.filter(i => items[i.id] && items[i.id].status === 'skipped');

  const totals = { ir: 0, pr: 0, ca: 0, vi: 0 };
  given.forEach(item => {
    const n = NUTRITION[item.id];
    if (n) {
      totals.ir += n.ir || 0;
      totals.pr += n.pr || 0;
      totals.ca += n.ca || 0;
      totals.vi += n.vi || 0;
    }
  });

  const html = `<!DOCTYPE html>
<html><head>
<meta charset="UTF-8">
<title>Amma Recovery Report — ${dayKey}</title>
<style>
  body{font-family:Arial,sans-serif;padding:20px;max-width:600px;margin:0 auto;color:#1a202c;}
  h1{color:#1a3a5c;font-size:22px;}
  h2{color:#1a6bbf;font-size:16px;margin-top:20px;}
  .badge{display:inline-block;padding:3px 9px;border-radius:8px;font-size:12px;font-weight:700;margin:3px;}
  .green{background:#eafaf1;color:#27ae60;}
  .red{background:#fdecea;color:#e74c3c;}
  .blue{background:#eaf2fb;color:#1a6bbf;}
  .item{padding:8px;border-bottom:1px solid #e2e8f0;font-size:14px;}
  .nut{margin:8px 0;font-size:14px;}
  footer{margin-top:30px;font-size:11px;color:#718096;text-align:center;}
</style>
</head><body>
<h1>Amma Recovery — Daily Report</h1>
<p><strong>Date:</strong> ${dayKey}</p>
<p><strong>BP Tablet (Telzun H 40mg):</strong> ${bp ? `Given at ${bpTime || 'N/A'}` : 'NOT MARKED'}</p>

<h2>Nutrition Totals</h2>
<div class="nut">🩸 Iron: ${totals.ir.toFixed(1)} mg (goal: 27 mg)</div>
<div class="nut">💪 Protein: ${totals.pr.toFixed(1)} g (goal: 60 g)</div>
<div class="nut">🔥 Calories: ${totals.ca} kcal (goal: 1800 kcal)</div>
<div class="nut">🍊 Vitamin C: ${totals.vi} mg (goal: 65 mg)</div>

<h2>Given / Eaten (${given.length} items)</h2>
${given.map(i => `<div class="item"><span class="badge green">✓</span> ${i.em} ${i.en} ${items[i.id]?.time ? '· ' + items[i.id].time : ''}</div>`).join('')}

<h2>Skipped (${skipped.length} items)</h2>
${skipped.length === 0 ? '<p style="color:#718096">None skipped</p>' : skipped.map(i => `<div class="item"><span class="badge red">✗</span> ${i.em} ${i.en}</div>`).join('')}

${extras.length > 0 ? `<h2>Extras Added (${extras.length})</h2>
${extras.map(ex => `<div class="item"><span class="badge blue">+</span> ${ex.name} ${ex.time ? '· ' + ex.time : ''} (${ex.shift})</div>`).join('')}` : ''}

<footer>Generated by Amma Recovery App — ${new Date().toLocaleString()}</footer>
</body></html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `amma-report-${dayKey}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function App() {
  const { lang } = useLang();
  const [currentPage, setCurrentPage] = useState('today');
  const [appData, setAppData] = useState(null);
  const [synced, setSynced] = useState(false);
  const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState({ type: null, data: {} });

  const sections = cookPattern ? buildDaySections(cookPattern) : null;
  const allItems = buildAllItems(sections);

  // Firebase listener
  useEffect(() => {
    const dbRef = ref(db, DB_KEY);
    const unsubscribe = onValue(
      dbRef,
      snap => {
        const val = snap.val() || {};
        setAppData(val);
        setSynced(true);
        setLoading(false);
      },
      err => {
        console.error('Firebase error:', err);
        setSynced(false);
        setLoading(false);
      }
    );
    return () => unsubscribe();
  }, []);

  const saveData = useCallback((newData) => {
    setAppData(newData);
    set(ref(db, DB_KEY), newData).catch(err => {
      console.error('Save error:', err);
      setSynced(false);
    });
  }, []);

  function getTodayData() {
    return (appData && appData[TODAY]) ? { ...appData[TODAY] } : emptyDay();
  }

  function onItemClick(itemId, sectionKey) {
    const todayData = getTodayData();
    const itemState = todayData.items && todayData.items[itemId];
    if (itemState && (itemState.status === 'done' || itemState.status === 'skipped')) {
      // Find label
      const item = allItems.find(i => i.id === itemId);
      const label = item ? (lang === 'te' && item.te ? item.te : item.en) : itemId;
      setModal({ type: 'undo', data: { itemId, label } });
    } else {
      setModal({ type: 'item', data: { itemId } });
    }
  }

  function markItem(status) {
    const itemId = modal.data?.itemId;
    if (!itemId) return;
    const todayData = getTodayData();
    todayData.items = { ...(todayData.items || {}), [itemId]: { status, time: nowStr() } };
    saveData({ ...appData, [TODAY]: todayData });
    setModal({ type: null, data: {} });
  }

  function undoItem() {
    const itemId = modal.data?.itemId;
    if (!itemId) return;
    const todayData = getTodayData();
    const newItems = { ...(todayData.items || {}) };
    delete newItems[itemId];
    todayData.items = newItems;
    saveData({ ...appData, [TODAY]: todayData });
    setModal({ type: null, data: {} });
  }

  function markBP() {
    const todayData = getTodayData();
    if (todayData.bp) {
      setModal({ type: 'bpundo', data: {} });
    } else {
      todayData.bp = true;
      todayData.bpTime = nowStr();
      saveData({ ...appData, [TODAY]: todayData });
    }
  }

  function bpUndo() {
    const todayData = getTodayData();
    todayData.bp = false;
    todayData.bpTime = null;
    saveData({ ...appData, [TODAY]: todayData });
    setModal({ type: null, data: {} });
  }

  function resetDay() {
    saveData({ ...appData, [TODAY]: emptyDay() });
    setModal({ type: null, data: {} });
  }

  function saveExtra(name, time, shift) {
    const todayData = getTodayData();
    const extras = [...(todayData.extras || []), { name, time, shift, addedAt: nowStr() }];
    todayData.extras = extras;
    saveData({ ...appData, [TODAY]: todayData });
    setModal({ type: null, data: {} });
  }

  function closeModal() {
    setModal({ type: null, data: {} });
  }

  function openHistDetail(dayKey, dayData) {
    setModal({ type: 'histdetail', data: { key: dayKey, data: dayData } });
  }

  function dlReport(dayKey) {
    const dayData = (appData && appData[dayKey]) || emptyDay();
    generateReport(dayKey, dayData, allItems);
  }

  function openHowTo(itemId, name) {
    setModal({ type: 'howtocook', data: { itemId, name } });
  }

  if (loading) {
    return (
      <div className="splash">
        <div className="splash-icon">🌿</div>
        <div className="splash-title">Amma Recovery</div>
        <div className="splash-sub">Loading...</div>
      </div>
    );
  }

  const todayData = getTodayData();

  return (
    <div>
      <Header synced={synced} />
      <SyncBar synced={synced} />

      {currentPage === 'today' && (
        <TodayPage
          appData={appData}
          today={TODAY}
          sections={sections}
          onItemClick={onItemClick}
          onMarkBP={markBP}
          onAddExtra={() => setModal({ type: 'extra', data: {} })}
          onReset={() => setModal({ type: 'reset', data: {} })}
        />
      )}
      {currentPage === 'history' && (
        <HistoryPage
          appData={appData}
          today={TODAY}
          allItems={allItems}
          onViewDay={openHistDetail}
          onReport={dlReport}
        />
      )}
      {currentPage === 'cook' && (
        <CookPage
          appData={appData}
          today={TODAY}
          cookPattern={cookPattern}
          saveData={saveData}
          onHowTo={openHowTo}
        />
      )}
      {currentPage === 'avoid' && <AvoidPage />}

      <BottomNav currentPage={currentPage} setPage={setCurrentPage} />

      <CookToast
        cookPattern={cookPattern}
        appData={appData}
        today={TODAY}
        saveData={saveData}
        setPage={setCurrentPage}
      />

      {/* Modals */}
      <ItemActionModal
        open={modal.type === 'item'}
        onDone={() => markItem('done')}
        onSkip={() => markItem('skipped')}
        onBack={closeModal}
      />
      <UndoModal
        open={modal.type === 'undo'}
        itemLabel={modal.data?.label}
        onReset={undoItem}
        onKeep={closeModal}
      />
      <BPUndoModal
        open={modal.type === 'bpundo'}
        onReset={bpUndo}
        onKeep={closeModal}
      />
      <ResetModal
        open={modal.type === 'reset'}
        onReset={resetDay}
        onCancel={closeModal}
      />
      <AddExtraModal
        open={modal.type === 'extra'}
        onSave={saveExtra}
        onCancel={closeModal}
      />
      <HistoryDetailModal
        open={modal.type === 'histdetail'}
        dayKey={modal.data?.key}
        dayData={modal.data?.data}
        allItems={allItems}
        onClose={closeModal}
        onReport={() => dlReport(modal.data?.key)}
      />
      <HowToCookModal
        open={modal.type === 'howtocook'}
        itemId={modal.data?.itemId}
        itemName={modal.data?.name}
        onClose={closeModal}
      />
    </div>
  );
}
